services:
  db:
    image: postgres:16.4
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "${S3_API_PORT}:9000"  # S3 API
      - "${MINIO_WEB_PORT}:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
volumes:
  db-data:
  minio-data:

